"""Step 4 兼容门面。

正文抓取主体逻辑已拆入 `content` 与 `steps.step4_content_fetch`。旧测试、CLI 和
外部调用仍可从本模块导入公开接口，但新增逻辑不得继续写在这里。
"""

from __future__ import annotations

from ..content.fetch import (
    AliyunIQSClient,
    build_aliyun_fetch_result,
    build_step4_checkpoint_entry_id,
    fetch_article_contents,
    fetch_once,
    fetch_result_from_dict,
    fetch_result_to_dict,
    fetch_selected_result_content,
    fetch_url_content,
    match_aliyun_document,
    normalize_request_url,
    should_skip_selected_url,
    urlopen,
)
from ..content.html import (
    VisibleTextParser,
    compact_text,
    decode_html,
    extract_c114_article_text,
    extract_content_text,
    extract_html_summary,
    extract_html_title,
    extract_visible_text,
    normalize_aliyun_published_at,
    normalize_compare_text,
    published_date_close,
    strip_c114_shell_sections,
    title_similarity,
)
from ..content.types import (
    VALID_KEEP_LEVELS,
    AliyunSearchDocument,
    ArticleContentPayload,
    ContentCategoryPayload,
    ContentWorkflowPayload,
    FetchOutputPaths,
    FetchResult,
    SearchContentArticleInput,
    SearchContentCategoryInput,
    SearchResultsInputPayload,
    SelectedContentPayload,
)
from ..content.yaml_io import (
    load_search_results_yaml,
    render_content_yaml,
    render_fetch_block,
    resolve_content_output_paths,
    save_content_results,
    search_workflow_to_search_results_input,
)
from utils.steps.step4_content_fetch import run_content_fetch_workflow, validate_content_fetch_inputs

__all__ = [
    "AliyunIQSClient",
    "AliyunSearchDocument",
    "ArticleContentPayload",
    "ContentCategoryPayload",
    "ContentWorkflowPayload",
    "FetchOutputPaths",
    "FetchResult",
    "SearchContentArticleInput",
    "SearchContentCategoryInput",
    "SearchResultsInputPayload",
    "SelectedContentPayload",
    "VALID_KEEP_LEVELS",
    "VisibleTextParser",
    "build_aliyun_fetch_result",
    "build_step4_checkpoint_entry_id",
    "compact_text",
    "decode_html",
    "extract_c114_article_text",
    "extract_content_text",
    "extract_html_summary",
    "extract_html_title",
    "extract_visible_text",
    "fetch_article_contents",
    "fetch_once",
    "fetch_result_from_dict",
    "fetch_result_to_dict",
    "fetch_selected_result_content",
    "fetch_url_content",
    "load_search_results_yaml",
    "match_aliyun_document",
    "normalize_aliyun_published_at",
    "normalize_compare_text",
    "normalize_request_url",
    "published_date_close",
    "render_content_yaml",
    "render_fetch_block",
    "resolve_content_output_paths",
    "run_content_fetch_workflow",
    "save_content_results",
    "search_workflow_to_search_results_input",
    "should_skip_selected_url",
    "strip_c114_shell_sections",
    "title_similarity",
    "urlopen",
    "validate_content_fetch_inputs",
]
