"""Local Selenium drag demo for studying browser mouse events.

This script only controls a local HTML file generated by this script. It does
not connect to websites, captcha widgets, or verification flows.

Usage:
    python scripts/research/selenium_local_drag_demo.py --write-page
    python scripts/research/selenium_local_drag_demo.py

Install dependency if needed:
    python -m pip install selenium
"""

from __future__ import annotations

import argparse
import math
import random
import time
from pathlib import Path


OUTPUT_DIR = Path("output/research/selenium_local_drag")
PAGE_PATH = OUTPUT_DIR / "drag_demo.html"


HTML = """<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Local Drag Demo</title>
  <style>
    body {
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      background: linear-gradient(135deg, #eaf3f8, #f8fbfd);
      font-family: "Segoe UI", "Microsoft YaHei", sans-serif;
      color: #102235;
    }
    .panel {
      width: min(720px, calc(100vw - 40px));
      padding: 30px;
      border-radius: 24px;
      background: white;
      border: 1px solid #dbe8f2;
      box-shadow: 0 20px 60px rgba(16, 34, 53, .12);
    }
    h1 {
      margin: 0 0 10px;
      font-size: 24px;
    }
    p {
      margin: 0 0 24px;
      color: #5c6f80;
      line-height: 1.7;
    }
    .track {
      position: relative;
      height: 58px;
      border-radius: 18px;
      background: #eef4f8;
      border: 1px solid #d3e2ed;
      overflow: hidden;
      user-select: none;
    }
    .progress {
      position: absolute;
      inset: 0 auto 0 0;
      width: 0;
      background: linear-gradient(90deg, #8ac2a4, #4da37a);
      opacity: .55;
    }
    .thumb {
      position: absolute;
      top: 7px;
      left: 7px;
      width: 44px;
      height: 44px;
      border-radius: 14px;
      background: #0f5ea8;
      box-shadow: 0 8px 18px rgba(15, 94, 168, .28);
      cursor: grab;
    }
    .thumb:active {
      cursor: grabbing;
    }
    .label {
      position: absolute;
      inset: 0;
      display: grid;
      place-items: center;
      pointer-events: none;
      font-weight: 700;
      color: #60788d;
    }
    .status {
      margin-top: 16px;
      padding: 12px 14px;
      border-radius: 14px;
      background: #f8fbfd;
      color: #33516c;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <main class="panel">
    <h1>本地拖拽研究页</h1>
    <p>这个页面只用于研究 Selenium 鼠标拖拽事件。它不是验证码，也不会提交任何验证结果。</p>
    <div id="track" class="track" aria-label="local drag track">
      <div id="progress" class="progress"></div>
      <div id="label" class="label">拖到右侧完成本地演示</div>
      <div id="thumb" class="thumb" role="button" aria-label="drag thumb"></div>
    </div>
    <div id="status" class="status">等待拖拽</div>
  </main>
  <script>
    const track = document.getElementById("track");
    const thumb = document.getElementById("thumb");
    const progress = document.getElementById("progress");
    const status = document.getElementById("status");
    let dragging = false;
    let startClientX = 0;
    let startLeft = 0;

    function maxLeft() {
      return track.clientWidth - thumb.clientWidth - 14;
    }
    function setLeft(left) {
      const clamped = Math.max(7, Math.min(maxLeft(), left));
      thumb.style.left = `${clamped}px`;
      progress.style.width = `${clamped + thumb.clientWidth / 2}px`;
      const ratio = Math.round((clamped - 7) / (maxLeft() - 7) * 100);
      status.textContent = ratio >= 98 ? "本地拖拽完成" : `拖拽进度：${ratio}%`;
    }
    thumb.addEventListener("pointerdown", (event) => {
      dragging = true;
      thumb.setPointerCapture(event.pointerId);
      startClientX = event.clientX;
      startLeft = thumb.offsetLeft;
    });
    thumb.addEventListener("pointermove", (event) => {
      if (!dragging) return;
      setLeft(startLeft + event.clientX - startClientX);
    });
    thumb.addEventListener("pointerup", (event) => {
      dragging = false;
      thumb.releasePointerCapture(event.pointerId);
    });
  </script>
</body>
</html>
"""


def write_page() -> Path:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    PAGE_PATH.write_text(HTML, encoding="utf-8")
    return PAGE_PATH.resolve()


def human_like_offsets(distance: int, steps: int = 40, seed: int = 23) -> list[tuple[int, int, float]]:
    """Return small x/y/delay offsets for local visualization-only dragging."""

    rng = random.Random(seed)
    points: list[tuple[int, int, float]] = []
    last_x = 0.0
    for index in range(steps):
        p = index / (steps - 1)
        ease = 1 - (1 - p) ** 3
        current_x = ease * distance
        dx = int(round(current_x - last_x))
        last_x = current_x
        y = int(round(math.sin(p * math.pi * 3) * rng.uniform(0.0, 1.8)))
        delay = rng.uniform(0.01, 0.035) if p < 0.8 else rng.uniform(0.025, 0.07)
        points.append((dx, y, delay))
    return points


def run_drag_demo(page_path: Path) -> None:
    try:
        from selenium import webdriver
        from selenium.webdriver.common.action_chains import ActionChains
        from selenium.webdriver.common.by import By
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "缺少 selenium。请先运行：python -m pip install selenium\n"
            "脚本只会控制本地 HTML 页面，不会访问真实网站。"
        ) from exc

    driver = webdriver.Chrome()
    try:
        driver.get(page_path.resolve().as_uri())
        thumb = driver.find_element(By.ID, "thumb")
        track = driver.find_element(By.ID, "track")
        distance = track.size["width"] - thumb.size["width"] - 18

        actions = ActionChains(driver)
        actions.move_to_element(thumb).click_and_hold()
        for dx, dy, delay in human_like_offsets(distance):
            actions.move_by_offset(dx, dy).pause(delay)
        actions.release().perform()
        time.sleep(1.0)
        print(driver.find_element(By.ID, "status").text)
    finally:
        driver.quit()


def main() -> None:
    parser = argparse.ArgumentParser(description="Local Selenium drag demo.")
    parser.add_argument("--write-page", action="store_true", help="Only write the local HTML page.")
    args = parser.parse_args()

    page = write_page()
    print(page)
    if not args.write_page:
        run_drag_demo(page)


if __name__ == "__main__":
    main()
